### ISSUE TITLE
Theme not working correctly after Discord update

### ISSUE THREAD

**Issue by vexxic** [ClearVision/ClearVision-v6#78] opened 2022-01-12 03:22 UTC
**Describe the bug**
After a Discord update, Theme is not transparent on "Home" screen and in Discord Settings

**To Reproduce**
1. Open Discord and navigate to "Home" screen or open Discord Settings

**Screenshots**
https://i.imgur.com/aUJaYTy.png

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19042)
 - Discord version: Stable 110451 (c233a73)
 - Client/BBD Version: BetterDiscord 1.3.0

**Additional context**

**Comment by untuned** [comment] 2022-01-12 07:33
Duplicate of #75.

**Closed by untuned** 2022-01-12 07:33 UTC
Labels: unverified bug
