### ISSUE TITLE
Theme does not work on latest version of Discord (BetterDiscord 1.3.0) + (Stable 110451 (c233a73)

### ISSUE THREAD

**Issue by Aholicknight** [ClearVision/ClearVision-v6#77] opened 2022-01-11 19:10 UTC
I installed the latest version of ClearVision onto BetterDiscord running version 1.3.0, after applying the theme this shows:
<img width="1321" alt="Screen Shot 2022-01-11 at 1 10 27 PM" src="https://user-images.githubusercontent.com/7843719/149006117-7531b1d0-47ad-4c87-9c95-a0e28e59eb1c.png">

The theme does not work after installing the latest version of Discord, will this be fixed soon? Thanks.

**Comment by Aria-NL** [comment] 2022-01-11 19:46
this is a duplicate of #75

**Comment by untuned** [comment] 2022-01-11 19:51
Duplicate of #75.

**Closed by untuned** 2022-01-11 19:51 UTC
Labels: unverified bug
