### ISSUE TITLE
[Bug Report] User modal popouts arent sized correctly

### ISSUE THREAD

**Issue by ExperiBass** [ClearVision/ClearVision-v6#83] opened 2022-01-24 23:26 UTC
### Did You Search Other Issues?

- [X] I have checked other issues

### Describe The Bug

When clicking on a user on the sidebar, the modal isn't properly formatted.

### Reproduction Steps

```bash
1. click on a user.
```

### Screenshots
![image](https://user-images.githubusercontent.com/33764485/150881979-17344a98-a3df-470b-b740-1461701fd091.png)

**Comment by untuned** [comment] 2022-01-25 00:55
Not reproducable on my end, could you post your theme file please?

**Comment by ExperiBass** [comment] 2022-01-25 03:02
[ebm.theme.css.zip](https://github.com/ClearVision/ClearVision-v6/files/7930287/ebm.theme.css.zip)

**Comment by NyxIsBad** [comment] 2022-01-27 22:04
Can you provide steps for reproduction? I can't get this to show up on. However, I cannot load your font so I can't test it properly

My guess is it's probably your oddly spaced font that's making things larger than the containers... well, containing them. I suggest using a different one that has standard spacing. 

If no further elaboration is provided for a period of time or it's determined that it _is_ the font, I suggest closing this issue because that would be outside our control

**Comment by ExperiBass** [comment] 2022-01-28 00:26
It seems to only happen when clicking on a user on the sidebar of servers. Im testing using a standard font (Consolas), the issue still happens, so unless Consolas is also borked that shouldn't be it.

![image](https://user-images.githubusercontent.com/33764485/151465688-83bf056f-6290-426d-977b-44ebca2cdc14.png)

**Comment by Leozard** [comment] 2022-01-29 18:11
Known issue due to the order things load, it usually only happens the first time you load a user's popout. Can't and won't fix for now

**Closed by Leozard** 2022-01-29 18:11 UTC
Labels: unverified bug
